export const posts = [
  {
    id: "post1",
    userId: "user15",
    image: "https://picsum.photos/800/800?random=1",
    caption: "This UI is clean af ✨",
    likes: ["user18", "user13", "user4"],
    comments: [
      { userId: "user16", text: "Big W 💯" },
      { userId: "user11", text: "Impressive!" },
    ],
    timestamp: "2025-05-02T11:52:27Z",
  },
  {
    id: "post2",
    userId: "user5",
    image: "https://picsum.photos/800/800?random=2",
    caption: "Vanilla JS supremacy 😤",
    likes: ["user1", "user6", "user11", "user17", "user4"],
    comments: [],
    timestamp: "2025-05-02T04:28:20Z",
  },
  {
    id: "post3",
    userId: "user7",
    image: "https://picsum.photos/800/800?random=3",
    caption: "New blog post up!",
    likes: [],
    comments: [
      { userId: "user5", text: "Killing it!" },
      { userId: "user3", text: "Looks great 🔥" },
    ],
    timestamp: "2025-05-03T20:13:40Z",
  },
  {
    id: "post4",
    userId: "user7",
    image: "https://picsum.photos/800/800?random=4",
    caption: "Firebase saves lives 🙏",
    likes: ["user15"],
    comments: [
      { userId: "user4", text: "Bookmarking this!" },
      { userId: "user20", text: "Teach me, sensei 🙇" },
    ],
    timestamp: "2025-05-02T09:40:01Z",
  },
  {
    id: "post5",
    userId: "user17",
    image: "https://picsum.photos/800/800?random=5",
    caption: "New project dropping soon 🎉",
    likes: [],
    comments: [],
    timestamp: "2025-05-03T09:06:42Z",
  },
  {
    id: "post6",
    userId: "user14",
    image: "https://picsum.photos/800/800?random=6",
    caption: "Productive coffee shop coding session ☕️",
    likes: [],
    comments: [
      { userId: "user1", text: "Can you share the repo?" },
      { userId: "user9", text: "Can you share the repo?" },
    ],
    timestamp: "2025-05-01T12:31:14Z",
  },
  {
    id: "post7",
    userId: "user13",
    image: "https://picsum.photos/800/800?random=7",
    caption: "Late night commits 🔥",
    likes: ["user2", "user11"],
    comments: [
      { userId: "user13", text: "Love this!" },
      { userId: "user18", text: "Can you share the repo?" },
      { userId: "user3", text: "Impressive!" },
    ],
    timestamp: "2025-05-01T05:37:10Z",
  },
  {
    id: "post8",
    userId: "user19",
    image: "https://picsum.photos/800/800?random=8",
    caption: "Weekend hackathon grind 💪",
    likes: ["user13", "user2", "user17"],
    comments: [],
    timestamp: "2025-05-02T12:43:09Z",
  },
  {
    id: "post9",
    userId: "user7",
    image: "https://picsum.photos/800/800?random=9",
    caption: "New blog post up!",
    likes: ["user12", "user2", "user4"],
    comments: [{ userId: "user20", text: "Teach me, sensei 🙇" }],
    timestamp: "2025-05-03T17:36:59Z",
  },
  {
    id: "post10",
    userId: "user16",
    image: "https://picsum.photos/800/800?random=10",
    caption: "Weekend hackathon grind 💪",
    likes: ["user13", "user4", "user20"],
    comments: [],
    timestamp: "2025-05-01T18:21:26Z",
  },
  {
    id: "post11",
    userId: "user12",
    image: "https://picsum.photos/800/800?random=11",
    caption: "Hot reload = happiness",
    likes: ["user14", "user20", "user16"],
    comments: [
      { userId: "user17", text: "Looks great 🔥" },
      { userId: "user15", text: "Impressive!" },
    ],
    timestamp: "2025-05-02T20:10:23Z",
  },
  {
    id: "post12",
    userId: "user13",
    image: "https://picsum.photos/800/800?random=12",
    caption: "Productive coffee shop coding session ☕️",
    likes: [],
    comments: [
      { userId: "user11", text: "Looks great 🔥" },
      { userId: "user12", text: "Love this!" },
    ],
    timestamp: "2025-05-03T09:35:53Z",
  },
  {
    id: "post13",
    userId: "user14",
    image: "https://picsum.photos/800/800?random=13",
    caption: "Testing is underrated!",
    likes: [],
    comments: [],
    timestamp: "2025-05-02T07:40:18Z",
  },
  {
    id: "post14",
    userId: "user1",
    image: "https://picsum.photos/800/800?random=14",
    caption: "New project dropping soon 🎉",
    likes: ["user14"],
    comments: [
      { userId: "user14", text: "Nice one!" },
      { userId: "user2", text: "Bookmarking this!" },
      { userId: "user11", text: "Impressive!" },
    ],
    timestamp: "2025-05-01T19:49:04Z",
  },
  {
    id: "post15",
    userId: "user8",
    image: "https://picsum.photos/800/800?random=15",
    caption: "From electronics to full-stack 🙌",
    likes: [],
    comments: [
      { userId: "user4", text: "Killing it!" },
      { userId: "user11", text: "Can you share the repo?" },
      { userId: "user7", text: "Impressive!" },
    ],
    timestamp: "2025-05-03T03:39:19Z",
  },
  {
    id: "post16",
    userId: "user7",
    image: "https://picsum.photos/800/800?random=16",
    caption: "Learning Next.js today!",
    likes: ["user10"],
    comments: [
      { userId: "user2", text: "Bookmarking this!" },
      { userId: "user8", text: "Bookmarking this!" },
      { userId: "user12", text: "Nice one!" },
    ],
    timestamp: "2025-05-02T00:32:01Z",
  },
  {
    id: "post17",
    userId: "user2",
    image: "https://picsum.photos/800/800?random=17",
    caption: "Typescripted everything ✍️",
    likes: ["user4", "user19", "user11"],
    comments: [],
    timestamp: "2025-05-02T19:22:04Z",
  },
  {
    id: "post18",
    userId: "user11",
    image: "https://picsum.photos/800/800?random=18",
    caption: "Firebase saves lives 🙏",
    likes: ["user1", "user6", "user16", "user3", "user20"],
    comments: [],
    timestamp: "2025-05-02T12:21:22Z",
  },
  {
    id: "post19",
    userId: "user10",
    image: "https://picsum.photos/800/800?random=19",
    caption: "Just launched my portfolio site 🚀",
    likes: [],
    comments: [
      { userId: "user8", text: "Impressive!" },
      { userId: "user20", text: "Love this!" },
    ],
    timestamp: "2025-05-01T09:55:41Z",
  },
  {
    id: "post20",
    userId: "user16",
    image: "https://picsum.photos/800/800?random=20",
    caption: "From electronics to full-stack 🙌",
    likes: [],
    comments: [{ userId: "user12", text: "Impressive!" }],
    timestamp: "2025-05-03T01:14:20Z",
  },
];
export const users = [
  {
    id: "user1",
    username: "user_1",
    name: "User 1",
    bio: "Bio of user 1",
    avatar: "https://i.pravatar.cc/150?img=1",
    followers: ["user6", "user4", "user17", "user19"],
    following: ["user17", "user14"],
    bookmarks: ["post1", "post5", "post10"], // Example bookmarks
  },
  {
    id: "user2",
    username: "user_2",
    name: "User 2",
    bio: "Bio of user 2",
    avatar: "https://i.pravatar.cc/150?img=2",
    followers: ["user13", "user6", "user10"],
    following: ["user4", "user8"],
    bookmarks: ["post2", "post8"], // Example bookmarks
  },
  {
    id: "user3",
    username: "user_3",
    name: "User 3",
    bio: "Bio of user 3",
    avatar: "https://i.pravatar.cc/150?img=3",
    followers: ["user15", "user2", "user10", "user17", "user12"],
    following: ["user8", "user9"],
    bookmarks: ["post3", "post7"], // Example bookmarks
  },
  {
    id: "user4",
    username: "user_4",
    name: "User 4",
    bio: "Bio of user 4",
    avatar: "https://i.pravatar.cc/150?img=4",
    followers: ["user8", "user17", "user1", "user9", "user20"],
    following: ["user5", "user10", "user13"],
    bookmarks: ["post4", "post6"], // Example bookmarks
  },
  {
    id: "user5",
    username: "user_5",
    name: "User 5",
    bio: "Bio of user 5",
    avatar: "https://i.pravatar.cc/150?img=5",
    followers: ["user20"],
    following: ["user16", "user2", "user9", "user8"],
    bookmarks: ["post9", "post12"], // Example bookmarks
  },
  {
    id: "user6",
    username: "user_6",
    name: "User 6",
    bio: "Bio of user 6",
    avatar: "https://i.pravatar.cc/150?img=6",
    followers: [],
    following: [],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user7",
    username: "user_7",
    name: "User 7",
    bio: "Bio of user 7",
    avatar: "https://i.pravatar.cc/150?img=7",
    followers: ["user2", "user10", "user1", "user17"],
    following: ["user15", "user10", "user6", "user8"],
    bookmarks: ["post11", "post14"], // Example bookmarks
  },
  {
    id: "user8",
    username: "user_8",
    name: "User 8",
    bio: "Bio of user 8",
    avatar: "https://i.pravatar.cc/150?img=8",
    followers: ["user6"],
    following: ["user1", "user10", "user20", "user18", "user16"],
    bookmarks: ["post13", "post15"], // Example bookmarks
  },
  {
    id: "user9",
    username: "user_9",
    name: "User 9",
    bio: "Bio of user 9",
    avatar: "https://i.pravatar.cc/150?img=9",
    followers: ["user16"],
    following: ["user4", "user6", "user17"],
    bookmarks: ["post16"], // Example bookmarks
  },
  {
    id: "user10",
    username: "user_10",
    name: "User 10",
    bio: "Bio of user 10",
    avatar: "https://i.pravatar.cc/150?img=10",
    followers: ["user15", "user16", "user7", "user12", "user3"],
    following: ["user12"],
    bookmarks: ["post17", "post18"], // Example bookmarks
  },
  {
    id: "user11",
    username: "user_11",
    name: "User 11",
    bio: "Bio of user 11",
    avatar: "https://i.pravatar.cc/150?img=11",
    followers: ["user18"],
    following: [],
    bookmarks: ["post19"], // Example bookmarks
  },
  {
    id: "user12",
    username: "user_12",
    name: "User 12",
    bio: "Bio of user 12",
    avatar: "https://i.pravatar.cc/150?img=12",
    followers: ["user18", "user8", "user1", "user9"],
    following: ["user2", "user19", "user14", "user17"],
    bookmarks: ["post20"], // Example bookmarks
  },
  {
    id: "user13",
    username: "user_13",
    name: "User 13",
    bio: "Bio of user 13",
    avatar: "https://i.pravatar.cc/150?img=13",
    followers: ["user6", "user8", "user12", "user1"],
    following: ["user5", "user12", "user15", "user16"],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user14",
    username: "user_14",
    name: "User 14",
    bio: "Bio of user 14",
    avatar: "https://i.pravatar.cc/150?img=14",
    followers: ["user20", "user12", "user15", "user6"],
    following: [],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user15",
    username: "user_15",
    name: "User 15",
    bio: "Bio of user 15",
    avatar: "https://i.pravatar.cc/150?img=15",
    followers: ["user4"],
    following: ["user10", "user2"],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user16",
    username: "user_16",
    name: "User 16",
    bio: "Bio of user 16",
    avatar: "https://i.pravatar.cc/150?img=16",
    followers: [],
    following: ["user19"],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user17",
    username: "user_17",
    name: "User 17",
    bio: "Bio of user 17",
    avatar: "https://i.pravatar.cc/150?img=17",
    followers: ["user13", "user19", "user12", "user15"],
    following: ["user13", "user6"],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user18",
    username: "user_18",
    name: "User 18",
    bio: "Bio of user 18",
    avatar: "https://i.pravatar.cc/150?img=18",
    followers: [],
    following: [],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user19",
    username: "user_19",
    name: "User 19",
    bio: "Bio of user 19",
    avatar: "https://i.pravatar.cc/150?img=19",
    followers: [],
    following: ["user3", "user2"],
    bookmarks: [], // No bookmarks
  },
  {
    id: "user20",
    username: "user_20",
    name: "User 20",
    bio: "Bio of user 20",
    avatar: "https://i.pravatar.cc/150?img=20",
    followers: ["user16", "user15", "user9", "user19", "user4"],
    following: ["user11"],
    bookmarks: [], // No bookmarks
  },
];
